### ISSUE TITLE
Elassandra loading 8GB file of 32 Million rows

### ISSUE THREAD

**Issue by weworksonam** [strapdata/openfoodfacts#3]
Hi
I am curious about loading large data sets into Cassandra using the cassandra api.  For example, I used the import script to load a 32 million rows of data of about 8GB size.  It took about 19 hours to import them.  I wonder what is taking so much time to load a 8GB file.  It seems that is a lot of time to take to load that not huge file.
Is it the "create" call that is doing something magic like building indexes in elasticsearch? https://github.com/strapdata/openfoodfacts/blob/master/meetup/import.py#L86

What would you recommend instead if there is another way?  I am currently looking at reading a line at a time from a file and doing a manual sql inserts.

**Comment by vroyer** [comment]
This python import script is not the best solution to quickly load data.
If a well remember, we have used a COPY FROM over CQL, see https://github.com/strapdata/openfoodfacts/blob/master/csvload.sh <https://github.com/strapdata/openfoodfacts/blob/master/csvload.sh>
You can even load-it in multi-thread with the setting NUMPROCESSES , see https://docs.datastax.com/en/dse/5.1/cql/cql/cql_reference/cqlsh_commands/cqlshCopy.html <https://docs.datastax.com/en/dse/5.1/cql/cql/cql_reference/cqlsh_commands/cqlshCopy.html>

**Comment by weworksonam** [comment]
I tried the COPY in CQL and kept getting errors such as connection timeouts.  It is not meant for more than 2 million rows per docs.  Now I am checking if sstableloader works.  But I am not sure how to convert a huge file like 8gb into a .db file.  Would you know?
